# Do not use in production!!!

version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    ports:
      - "5432:5432"
    volumes:
      - ct-events-postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ct-events-redis:/var/lib/redis/data
  directus:
    image: directus/directus:10.10.4
    ports:
      - "8091:8055"
    environment:
      DB_CLIENT: "pg"
      KEY: "some random secret"
      SECRET: "another random secret"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "ct_events_api_development"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      STORAGE_LOCATIONS: "LOCAL"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "./local/"
      ADMIN_EMAIL: "admin@synthbit.io"
      ADMIN_PASSWORD: "Tw1l1ght932008"
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads
    depends_on:
      - postgres

volumes:
  ct-events-redis:
  ct-events-postgres:
