development:
  adapter: postgresql
  encoding: unicode
  pool: 50
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: ct_events_api_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 50
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: ct_events_api_test

production:
  database: ct_events_api_production
  username: ct_events_api
  password: <%= ENV["CT_EVENTS_API_DATABASE_PASSWORD"] %>
